# Generated by Django 3.0.8 on 2020-07-16 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paradigm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='language',
            name='paradism',
        ),
        migrations.AddField(
            model_name='language',
            name='paradigm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='languages.Paradigm'),
        ),
    ]
